
#pragma once
#include <Windows.h>
#include <GLFW/glfw3.h>
#include <glad/glad.h>
#include <ostream>
#include <string>
#include <map>
#include <vector>
#include <stack>
#include <filesystem>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <fstream>
#include <sstream>
#include <iostream>
#include <functional>
#include <assimp\Importer.hpp>
#include <assimp\scene.h>
#include <assimp\postprocess.h>